name: Spell Check

on:
  workflow_call:

permissions: {}

jobs:
  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Search for misspellings
        uses: crate-ci/typos@512fc24f32f44ab01972217aaaf3dc86ec234d53 # v1.50.2
        with:
          config: ./.github/typos.toml
